/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Quicknote;

import controller.ProjectController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import util.ConnectionFactory;
import static util.ConnectionFactory.closeConnection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        // iniciar uma conexão com o banco de dados
        Connection connection = ConnectionFactory.getConnection();
        
        ProjectController projectController = new ProjectController();
//        Project project = new Project();
//        project.setName("Projeto Olá Mundo");
//        project.setCreatedAt(new Date());
//        project.setDescription("Projecto criado para testar a aplicação");
//        projectController.save(project);
//        System.out.println(project);
        
        
//        project.setName("Novo Nome");
//        project.setDescription("Nova descrição.");
//        project.setId(1);
//        projectController.update(project);
//        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        System.out.println(projects);
                
                
        
        
        
        
        
        // encerrar a conexão com o banco de dados
        closeConnection(connection);
    }
}
